overrides:
  "katex@>=0.11.0 <0.16.10": ">=0.16.10"
  "katex@>=0.15.4 <0.16.10": ">=0.16.10"
  "katex@>=0.10.0-beta <0.16.10": ">=0.16.10"
  "express@<4.19.2": ">=4.19.2"
  "braces@<3.0.3": ">=3.0.3"
  "ws@>=8.0.0 <8.17.1": ">=8.17.1"
  "micromatch@<4.0.8": ">=4.0.8"
  "webpack@>=5.0.0-alpha.0 <5.94.0": ">=5.94.0"
  "body-parser@<1.20.3": ">=1.20.3"
  "serve-static@<1.16.0": ">=1.16.0"
  "express@<4.20.0": ">=4.20.0"
  "path-to-regexp@<0.1.10": ">=0.1.10"
  "cookie@<0.7.0": ">=0.7.0"
  "cross-spawn@<6.0.6": ">=6.0.6"
  "cross-spawn@>=7.0.0 <7.0.5": ">=7.0.5"
  "path-to-regexp@<0.1.12": ">=0.1.12"
  "brace-expansion@>=1.0.0 <=1.1.11": "^1.1.12"
  "brace-expansion@>=2.0.0 <=2.0.1": "^2.0.2"
  "katex@>=0.12.0 <=0.16.20": ">=0.16.21"
  "send@<0.19.0": ">=0.19.0"
  "nanoid@<3.3.8": ">=3.3.8"
  "postcss@<8.4.31": ">=8.4.31"
  "glob@>=10.2.0 <10.5.0": ">=10.5.0"
  "mdast-util-to-hast@>=13.0.0 <13.2.1": ">=13.2.1"

allowBuilds:
  "@vercel/speed-insights": true
  "sharp": true
  "unrs-resolver": true
  "@tailwindcss/oxide": true
